{
  model_features_dictionary_1 : {
  "model_name": "svm_rbf_win35",
  "C": 10 ** -2.1,
  "gamma": 10 ** -2.2,
  "window": 35,
  "kernel": "rbf",
  "feature_names": [ 'volume', 'pctChange', 'upperShadow', 'lowerShadow' ],
  "history_features": [ 'volume', 'pctChange', 'upperShadow', 'lowerShadow' ]
},
  model_features_dictionary_2 : {
  "model_name": "svm_rbf_win29",
  "C": 10 ** 0.5,
  "gamma": 10 ** -1.09,
  "window": 29,
  "kernel": "rbf",
  "feature_names": [ 'volume', 'close', 'high', 'low' ],
  "history_features": [ 'volume', 'close', 'high', 'low' ]
}
}